// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXpvnskX1CInHPOuZg8C9p9CgfrloFC2U',
    appId: '1:367228748745:web:8009e0846a9e399665de18',
    messagingSenderId: '367228748745',
    projectId: 'chatsy-2b7aa',
    authDomain: 'chatsy-2b7aa.firebaseapp.com',
    storageBucket: 'chatsy-2b7aa.firebasestorage.app',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGa6dkwF2E08ytlD7shPVVEK4LJCBI7c',
    appId: '1:367228748745:android:3f9eac21fc1a7d1e65de18',
    messagingSenderId: '367228748745',
    projectId: 'chatsy-2b7aa',
    storageBucket: 'chatsy-2b7aa.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5K0u2WfDOFKdnvSOgkUl7PPEfyiFqi94',
    appId: '1:367228748745:ios:6e4b5421c115b95b65de18',
    messagingSenderId: '367228748745',
    projectId: 'chatsy-2b7aa',
    storageBucket: 'chatsy-2b7aa.firebasestorage.app',
    iosBundleId: 'com.example.chatsy',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5K0u2WfDOFKdnvSOgkUl7PPEfyiFqi94',
    appId: '1:367228748745:ios:6e4b5421c115b95b65de18',
    messagingSenderId: '367228748745',
    projectId: 'chatsy-2b7aa',
    storageBucket: 'chatsy-2b7aa.firebasestorage.app',
    iosBundleId: 'com.example.chatsy',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXpvnskX1CInHPOuZg8C9p9CgfrloFC2U',
    appId: '1:367228748745:web:6c5311a5f14dcd9165de18',
    messagingSenderId: '367228748745',
    projectId: 'chatsy-2b7aa',
    authDomain: 'chatsy-2b7aa.firebaseapp.com',
    storageBucket: 'chatsy-2b7aa.firebasestorage.app',
  );
}
